name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build and check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      # rustfmt will check if the code build before checking the formatting.
      # Because the build script generated a new module in the code,
      # building the code before checking it is needed.
    - name: Check formatting
      run: cargo fmt --all -- --check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo test --verbose

  linting:
    name: Execute clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo clippy

